### ISSUE TITLE
After configuring the plugin, successful AAD login but SonarQube rejects with unauthorized

### ISSUE THREAD

**Issue by sewalshmsft** [hkamel/sonar-auth-aad#106]
Hi, 

I feeling I'm missing something obvious: whenever I authenticate with AAD, I get an unauthorized error from SonarQube. 

I configured the tenant/client ID/secrets correctly, I'm at a loss of why it's refusing the token.

**Comment by srvrguy** [comment]
If you're using IIS as a reverse proxy, check the solution at https://github.com/hkamel/sonar-auth-aad/wiki/Troubleshooting#im-never-getting-sent-to-the-microsoft-login-page and see if that helps.

If you aren't using IIS, can you provide more details on your configuration?

**Comment by sewalshmsft** [comment]
Yes, IIS reverse proxy.

AAD redirects back to the SonarQube server just fine but the AAD plugin doesn’t like the token for some reason.

**Comment by sewalshmsft** [comment]
I should add I was also able to build a new one from scratch in my own lab environment and was able to successfully login (using a different AAD tenant) but I’m at a loss as to why this customer instance doesn’t work.

From: Sean Walsh
Sent: Friday, July 17, 2020 2:08 PM
To: hkamel/sonar-auth-aad <reply@reply.github.com>
Subject: RE: [hkamel/sonar-auth-aad] After configuring the plugin, successful AAD login but SonarQube rejects with unauthorized (#106)

Yes, IIS reverse proxy.

AAD redirects back to the SonarQube server just fine but the AAD plugin doesn’t like the token for some reason.

**Comment by andrei-dascalu** [comment]
I am having the same issue. Setup seems ok, authentication works and I get redirected back, but eventually I land on:

`<myurl>/sessions/unauthorized`

And I see:

`You're not authorized to access this page. Please contact the administrator.`

**Comment by sewalshmsft** [comment]
@andrei-dascalu  What do you mean you get around the issue by enabling sign up? Can you explain in more detail?

Thanks!

**Comment by sewalshmsft** [comment]
I figured it out, one of the other admins entered the proxy URL incorrectly in the sonar.properies.  They put it as http://proxyserver.local instead of proxyserver.local. 

The web.log poined me in the right direction:

```
2020.08.04 14:42:36 INFO  web[AXO5R/gx02mHwr8TAAKh][o.s.s.l.ServerLogging] Level of logs changed to DEBUG
2020.08.04 14:42:37 DEBUG web[AXO5R/gx02mHwr8TAAKi][s.n.w.p.h.HttpURLConnection] sun.net.www.MessageHeader@3c38e2945 pairs: {GET /systemInfo HTTP/1.1: null}{User-Agent: SonarQube 8.3.1.34397 # 64385B38-AXKAzicMZsixbA91d-Q2 Java/11.0.7}{Host: 127.0.0.1:49958}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
2020.08.04 14:42:37 DEBUG web[AXO5R/gx02mHwr8TAAKi][s.n.w.p.h.HttpURLConnection] sun.net.www.MessageHeader@d4379735 pairs: {null: HTTP/1.1 200 OK}{Content-Type: application/x-protobuf}{Date: Tue, 4 Aug 2020 18:42:37 GMT}{Connection: keep-alive}{Content-Length: 8315}
2020.08.04 14:43:23 INFO  web[][c.m.a.a.AuthenticationAuthority] [Correlation ID: 01f1a3f2-2aeb-4613-a2e3-9890914d732c] Instance discovery was successful
2020.08.04 14:43:23 ERROR web[][c.m.a.a.AuthenticationContext] [Correlation ID: 01f1a3f2-2aeb-4613-a2e3-9890914d732c] Execution of class com.microsoft.aad.adal4j.AcquireTokenCallable failed.
java.net.UnknownHostException: http://{URL-REMOVED}
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
	at java.base/java.net.Socket.connect(Socket.java:608)
	at java.base/java.net.Socket.connect(Socket.java:557)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient$1.run(HttpClient.java:526)
	at java.base/sun.net.www.http.HttpClient$1.run(HttpClient.java:524)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.http.HttpClient.privilegedOpenServer(HttpClient.java:523)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:564)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1362)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1337)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:246)
	at com.microsoft.aad.adal4j.AdalOAuthRequest.configureHeaderAndExecuteOAuthCall(AdalOAuthRequest.java:145)
	at com.microsoft.aad.adal4j.AdalOAuthRequest.send(AdalOAuthRequest.java:83)
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:86)
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:928)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38)
	at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020.08.04 14:43:23 ERROR web[AXO5R/gx02mHwr8TAALH][o.a.a.a.AadIdentityProvider] Exception:java.util.concurrent.ExecutionException: java.net.UnknownHostException: http://{URL-REMOVED}
2020.08.04 14:43:23 DEBUG web[AXO5R/gx02mHwr8TAALH][auth.event] login failure [cause|Plugin did not call authenticate][method|OAUTH2][provider|EXTERNAL|Microsoft][IP|fe80:0:0:0:2563:fb0e:9e1:438c%3|10.0.3.9:40638][login|]
2020.08.04 14:46:34 INFO  web[AXO5R/gx02mHwr8TAALM][o.s.s.l.ServerLogging] Level of logs changed to INFO

```

**Comment by katlimruiz** [comment]
In my case, I found in SonarQube/Administration/System/Download Logs/WebServer and found this:

`2020.08.21 05:32:01 ERROR web[AXQPaRdyukYvx/zZAAFU][o.a.a.a.AadIdentityProvider] Exception:org.sonar.server.authentication.event.AuthenticationException: User signup disabled for provider 'aad'`

This means that the signup was disabled for Azure Active Directory, which was indeed turned off. I turned on, and it is now working.
