### ISSUE TITLE
OAuth2 Authorization code was already redeemed

### ISSUE THREAD

**Issue by extravio** [hkamel/sonar-auth-aad#127]
Hi, 
I'm running SonarQube community Edition 9.2.4 with version 1.2.0 of the plugin.
Authentication has been working well, but today I've tried to enable Groups Synchronization and I get a: 
**504 Gateway Time-out**.

In the logs I can see the following error:

```
2022.03.06 23:36:24 ERROR web[][c.m.a.a.AuthenticationContext] [Correlation ID: 1420457b-40cc-43a0-b0f3-ca5e5eede43a] Execution of class com.microsoft.aad.adal4j.AcquireTokenCallable failed.
com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token.\r\nTrace ID: 22a82219-3d46-4b1a-9d2d-b5513d371f00\r\nCorrelation ID: 1420457b-40cc-43a0-b0f3-ca5e5eede43a\r\nTimestamp: 2022-03-06 23:36:24Z","error":"invalid_grant"}
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:128)
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:928)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38)
	at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022.03.06 23:36:24 ERROR web[AX9RrW3vAaottjzxAAXP][o.a.a.a.AadIdentityProvider] Exception:java.util.concurrent.ExecutionException: com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token.\r\nTrace ID: 22a82219-3d46-4b1a-9d2d-b5513d371f00\r\nCorrelation ID: 1420457b-40cc-43a0-b0f3-ca5e5eede43a\r\nTimestamp: 2022-03-06 23:36:24Z","error":"invalid_grant"}
2022.03.06 23:36:35 INFO  web[][c.m.a.a.AuthenticationAuthority] [Correlation ID: 28c9f318-e4c1-4a0e-82c1-3fc804e81072] Instance discovery was successful
2022.03.06 23:37:08 ERROR web[AX9RrW3vAaottjzxAAXO][o.a.a.a.AadIdentityProvider] java.net.ConnectException: Operation timed out (Connection timed out)
2022.03.06 23:38:46 ERROR web[AX9RrW3vAaottjzxAAXc][o.a.a.a.AadIdentityProvider] java.net.ConnectException: Operation timed out (Connection timed out)
2022.03.06 23:54:52 INFO  web[][c.m.a.a.AuthenticationAuthority] [Correlation ID: ee1e3854-5977-4472-a743-cba50a0d9c5a] Instance discovery was successful
2022.03.06 23:57:02 ERROR web[AX9RrW3vAaottjzxAAYj][o.a.a.a.AadIdentityProvider] java.net.ConnectException: Operation timed out (Connection timed out)
```
I've followed the [wiki](https://github.com/hkamel/sonar-auth-aad/wiki/Group-Sync) and the API permissions are configured correctly.

The error occurred for both an existing user and a new user.

Any suggestions?

**Comment by srvrguy** [comment]
That is... odd. I can't reproduce it on my end with SQ 9.2. Perhaps it was a glitch on the MS side. Can you confirm if you're still seeing the issue?

**Comment by extravio** [comment]
We've upgraded to Community Edition 9.3.0 and we've got the same issue.
When "Groups Synchronization" is enabled if a user tries to log in, he gets a time-out and he's removed from all his existing groups.

**Comment by extravio** [comment]
Just FYI, we got it to work by adding the **GroupMember.Read.All** and **GroupMember.Read.All** to the permissions of the App Registration.
