### ISSUE TITLE
Your Not authorize to access this page 

### ISSUE THREAD

**Issue by mikproof** [hkamel/sonar-auth-aad#146]
I am getting an "you're not authorize to access this page", can't seem to figure out why I am getting this message, I setup my client Id, client secret. and tenant information. So I am wondering why I am getting this error message in my logs, when trying to login to sonarqube.

```
ERROR web[][c.m.a.a.AuthenticationContext] [Correlation ID: ] Execution of class com.microsoft.aad.adal4j.AcquireTokenCallable failed.
com.microsoft.aad.adal4j.AuthenticationException: {"error":"invalid_request","error_uri":"https:\/\/login.microsoftonline.us\/error?code=50146"}
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:128)
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:930)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38)
	at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023.01.20 16:27:34 ERROR web[AYXPzw7l6p19Tnx7AARp][o.a.a.a.AadIdentityProvider] Exception:java.util.concurrent.ExecutionException: com.microsoft.aad.adal4j.AuthenticationException: {"error":"invalid_request","error_uri":"https:\/\/login.microsoftonline.us\/error?code=50146"}
```

**Comment by franciscolopezc** [comment]
Hello! I'm having the same problem, what was the solution? Thanks!
