### ISSUE TITLE
AADSTS 50146 error when "Log in with M$"

### ISSUE THREAD

**Issue by cRaZyT1807** [hkamel/sonar-auth-aad#148]
Hi,
My setup looks like this:
- Docker Container:
  - SonarQube Developer Edition 8.9
- Azure :
```
| API / Permissions name | Typ         | 
| GroupMember.Read.All   | Application |
| profile                | Delegated   |
| User.ReadBasic.All     | Application |

- ID tokens (used for implicit and hybrid flows)
- Certificates & secrets created
```
- Plugin:
  - Allow users to sign-up enabled
  - Group Sync disabled
  - Multi Tenant disabled

I have configured the plugin and everything on Azure. I also can see that the login was successful in the Enterprise Application:
`2/21/2023, 3:50:50 PM | 8cddbb36-df0c-45af-9da9-320323d42d00 | Thorsten | sandbox-sonarqube | Success | x.x.x.x | Success | Multifactor authentication`

But in SonarQube I get the following error:
`You're not authorized to access this page. Please contact the administrator.`

And in the SonarQube Log there is the following:
> `2023.02.21 14:50:50 INFO  web[][c.m.a.a.AuthenticationAuthority] [Correlation ID: caf4031f-fcaa-4a54-b1da-a4792471e508] Instance discovery was successful
> 2023.02.21 14:50:50 ERROR web[][c.m.a.a.AuthenticationContext] [Correlation ID: caf4031f-fcaa-4a54-b1da-a4792471e508] Execution of class com.microsoft.aad.adal4j.AcquireTokenCallable failed.
> com.microsoft.aad.adal4j.AuthenticationException: {"error":"invalid_request","error_uri":"https:\/\/login.microsoftonline.com\/error?code=50146"}
> 	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:128)
> 	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:930)
> 	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70)
> 	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38)
> 	at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47)
> 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.base/java.lang.Thread.run(Unknown Source)
> 2023.02.21 14:50:50 ERROR web[AYZ0Z45Jo8zjzXltAACG][o.a.a.a.AadIdentityProvider] Exception:java.util.concurrent.ExecutionException: com.microsoft.aad.adal4j.AuthenticationException: {"error":"invalid_request","error_uri":"https:\/\/login.microsoftonline.com\/error?code=50146"}`

Where does the problem come from and how can I fix it?

Reards
Thorsten

**Comment by cRaZyT1807** [comment]
Hi,

I found the problem myself, in the Azure App registration the following value had to be set in the manifest:

> "acceptMappedClaims": true,

I have another problem, but I'll open a new ticket for that.

Regards
Thorsten
